# Generated by Django 5.2.8 on 2025-11-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_as', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DHCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('subnet', models.CharField(max_length=255)),
                ('default_router', models.CharField(max_length=255)),
                ('option150_tftp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('mgmt_ip', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('device_username', models.CharField(max_length=255)),
                ('device_password', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('base_dir', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BGPNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('remote_as', models.CharField(max_length=255)),
                ('bgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_bgp_neighbors', to='ztp.bgp')),
            ],
        ),
        migrations.CreateModel(
            name='BGPNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=255)),
                ('mask', models.CharField(max_length=255)),
                ('bgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_bgp_networks', to='ztp.bgp')),
            ],
        ),
        migrations.AddField(
            model_name='bgp',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_bgp', to='ztp.host'),
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('mask', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_interfaces', to='ztp.host')),
            ],
        ),
        migrations.CreateModel(
            name='StaticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('mask', models.CharField(max_length=255)),
                ('next_hop', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_static_routes', to='ztp.host')),
            ],
        ),
    ]
