# Generated by Django 5.2.8 on 2025-11-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpneighbor',
            old_name='ipaddress',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='dhcpserver',
            old_name='ipadd_address',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='ipaddress',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='scpserver',
            old_name='ipadd_address',
            new_name='ip_address',
        ),
    ]
