# Generated by Django 5.2.8 on 2025-11-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhcpserver',
            old_name='subnet',
            new_name='network',
        ),
    ]
