# Generated by Django 5.2.8 on 2025-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztp', '0002_rename_subnet_dhcpserver_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='mask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
